<?php

namespace RollRollBundle\Repository;

/**
 * GridRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GridRepository extends \Doctrine\ORM\EntityRepository
{
	public function getMax($game)
	{
		return $this->getEntityManager()->createQuery('
			SELECT max(a.playerOrder)
			FROM RollRollBundle:Grid a
			WHERE a.game = :game
		')->setParameter('game',$game)->getSingleScalarResult();
	}

	public function findNbPlayers($game)
	{
		return $this->getEntityManager()->createQuery('
			SELECT count(a)
			FROM RollRollBundle:Grid a
			WHERE a.game = :game
		')->setParameter('game',$game)->getSingleScalarResult();
	}
}
